version: "3.1"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: faces
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - $PWD/postgres:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"

  env:
    build: env-image

  app:
    build: ..
    ports:
      - "5000:5000"

  ui:
    build: ../ui
    ports:
      - "3000:3000"